name: 'Gitbook-Action'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'  # To Avoid Loop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2

    # example1
    - name: Gitbook Action # https://github.com/ZanderZhao/gitbook-action/releases
      uses: ZanderZhao/gitbook-action@master  # -> or ZanderZhao/gitbook-action@v1.2.4, Just example, click above, use latest please
      with:                                   #    or fork this repo and use YourName/gitbook-action@master
        token: ${{ secrets.PERSONAL_TOKEN }}  # -> remember add this in settings/secrets as https://ZanderZhao.github.io/gitbook-action/
        time_zone: Europe/Berlin
        source_branch: main
        source_dir: EVES
        source_edit_time: true
        publish_commit_message: ${{ github.event.head_commit.message }}
        publish_branch: gh-pages
        publish_dir: .